apiVersion: apps/v1
kind: Deployment
metadata: 
  name: healthcare-app
  labels:
    app: healthcare-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: healthcare-app
  template:
    metadata:
      labels: 
        app: healthcare-app
    spec:
      imagePullSecrets:
      - name: myregcred
      containers:
      - name: java-maven
        image: iamabhi1997/my-apps:Healthcare-app-2.0.0
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-app-service
spec:
  selector:
    app: healthcare-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
    nodePort: 30000